DROP DATABASE IF EXISTS BBDD;
CREATE DATABASE BBDD;
use BBDD

CREATE TABLE tab2 (
col1 VARCHAR(30), 
col2 VARCHAR(30), 
col3 INT, 
col4 VARCHAR(10),
PRIMARY KEY(col3,col4)
);

CREATE TABLE tab1 (
col1 INTEGER(5),
col2 CHAR(25) NOT NULL,
col3 INT,
col4 VARCHAR(10),
PRIMARY KEY (col1,col2),
CONSTRAINT fk1_col3 FOREIGN KEY (col3,col4) REFERENCES tab2(col3,col4)
);
